name: Run Feature Pipeline Notebook

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行一次

jobs:
  feature-pipeline:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 运行环境

    steps:
      # Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter hopsworks pandas requests

      # Run the Jupyter notebook using nbconvert
      - name: Run daily feature pipeline notebook
        run: |
          jupyter nbconvert --to notebook --execute 2_daily-feature-pipeline.ipynb --output 2_daily-feature-pipeline-executed.ipynb

      # Upload the result to GitHub (optional)
      - name: Upload executed notebook
        uses: actions/upload-artifact@v2
        with:
          name: executed-notebook
          path: 2_daily-feature-pipeline-executed.ipynb
