name: air-quality-daily

on:
  workflow_dispatch:
    schedule:
    - cron: '11 6 * * *'

jobs:
  schedule_pipelines:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      contents: write

    steps:
      - name: execute python workflows from bash script
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: 
          jupyter nbconvert --to notebook --execute 2_daily-feature-pipeline.ipynb
